### ISSUE TITLE
compilation issues

### ISSUE THREAD

**Issue by sdewell** [mlux86/acdc#2]
Thank for any insights!

ubuntu 14.04
boost 1_55 and cmake 3.14.5

inside build directory cmake .. works fine. 

then make -j4 goes:
...
Scanning dependencies of target acdc
[ 91%] Building CXX object src/CMakeFiles/acdc.dir/main.cpp.o
[ 92%] Linking CXX executable ../acdc
libmainprog.a(IOUtil.cpp.o): In function `IOUtil::copyDir(boost::filesystem::path const&, boost::filesystem::path const&, bool)':
IOUtil.cpp:(.text+0x596): undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
IOUtil.cpp:(.text+0x658): undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[2]: *** [acdc] Error 1
make[1]: *** [src/CMakeFiles/acdc.dir/all] Error 2
make: *** [all] Error 2

thanks!

**Comment by sdewell** [comment]
made my own container and it seems to be working. 

this error happens but don't really mind:
kraken: database ("/krakendb") does not contain necessary file database.kdb

thanks!
-scott

**Comment by sdewell** [comment]
and ... is there a way to skip RNAmmer? not using 16S always.

one application of mine is actually large numbers of raw reads with potential for dimers that are problematic.

and, perhaps be able to provide a sequence that -is- identifying to take the place of the 16S sequence? 

thanks, love the tool so far.

**Comment by mlx404** [comment]
Hi sdewell - I'm currently away until next Tuesday without access to a computer. I'll get back to you on that issue afterwards.

**Comment by mlx404** [comment]
@sdewell RNAmmer should be automatically skipped as soon as the rnammer executable could not be found or returns a return code different from zero. As for the Kraken issue, perhaps the database is corrupted or there is a newer version of it.
The other issue has been resolved already, has it?
Cheers,
Markus

**Comment by sdewell** [comment]
Thank you Markus,

Will look into RNAmmer and Kraken ... for now it's not a big issue for me.

I've been using docker as I had difficulty with boost, this is fine for me
for now

Is it possible somehow to extract the X,Y coordinates for the t-sne plots?
I can see about extracting them from the existing files if not. Thanks
again!

-s

**Comment by mlx404** [comment]
> Is it possible somehow to extract the X,Y coordinates for the t-sne plots? I can see about extracting them from the existing files if not. Thanks again!

Yes. Once acdc has run, look into the results folder. There should be a YAML file named after the input fasta. You can use a yaml reader to extract the t-sne coordinates from the YAML file using the "visualizations.sne" key. The two sub-keys "x1" and "x2" represent the x and y coordinates of t-SNE.
