### ISSUE TITLE
different compilation issues with boost ("No suitable build variant has been found.")

### ISSUE THREAD

**Issue by jvollme** [mlux86/acdc#3]
Hi, 
I downloaded the most recent acdc repository and tried to compile it according to the installation instructions. However, after running ```cmake ..``` from within the build subdirectory created within the acdc repository-folder, i get the following error:

```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost 1.70.0 at /home/ww5070/.conda/envs/sagabin_env/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS program_options;system;filesystem
-- Found boost_headers 1.70.0 at /home/ww5070/.conda/envs/sagabin_env/lib/cmake/boost_headers-1.70.0
-- Found boost_program_options 1.70.0 at /home/ww5070/.conda/envs/sagabin_env/lib/cmake/boost_program_options-1.70.0
-- No suitable boost_program_options variant has been identified!
--   libboost_program_options.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)
--   libboost_program_options.a (static, Boost_USE_STATIC_LIBS=OFF)
CMake Error at /home/ww5070/.conda/envs/sagabin_env/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Found package configuration file:

    /home/ww5070/.conda/envs/sagabin_env/lib/cmake/boost_program_options-1.70.0/boost_program_options-config.cmake

  but it set boost_program_options_FOUND to FALSE so package
  "boost_program_options" is considered to be NOT FOUND.  Reason given by
  package:

  No suitable build variant has been found.

Call Stack (most recent call first):
  /home/ww5070/.conda/envs/sagabin_env/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:242 (find_package)
  CMakeLists.txt:12 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ww5070/src/acdc/build/CMakeFiles/CMakeOutput.log".
```
Can you tell what I am doing wrong?

**Comment by mlx404** [comment]
Hi @jvollme - glad to hear someone is still having interest in the project - it's been a while.

From your logs it appears that you don't have a complete installation of boost available on your system. As stated in the README, you need program_options, system, filesystem.

On Debian or Ubuntu you should be able to install the boost dependency using `sudo apt-get install libboost-dev` - although I cannot test this right now as I don't have such an installation available atm.

On my current system however, I could successfully compile acdc - after fixing a minor issue - so please update to the latest version I just pushed. 

Let me know if installing boost helped.

**Comment by mlx404** [comment]
Oh, and please double check whether you use the correct location for boost - `/home/ww5070/.conda/envs/sagabin_env/lib/cmake/` is very likely not the version you want to use (only if you actually intended to).

**Comment by jvollme** [comment]
Actually, I had severe problems with fiddling boost installations in the past, so i generally like to use the conda versions. so actually that is the version I hoped to be able to use.
But i'll try outside of my conda environments with the global boost installation.

**Comment by jvollme** [comment]
thanks, indeed it worked.
In case anybody else has a similar issue: libboost-dev, which was already installed globally also, is apparently also not enough to for a full bost installation that includes all the required boost-libraries (at least on debian).
Each individual boost library has to be installed seperately:
````
 sudo apt install libboost-dev libboost-system-dev libboost-program-options-dev libboost-filesystem-dev
